import React from "react";
import type { Metadata } from "next";
import About from "@/components/about/about";

export const metadata: Metadata = {
	title: "About | Creativity is centar to our design",
	description: "Generated by https://taufiqproject.my.id",
};

export default function AboutPage() {
	return (
		<>
			<About />
		</>
	);
}
