import React from 'react';
import type { Metadata } from 'next';
import UiUxDesign from '@/components/capabilities/uiuxdesign/uiuxdesign';

export const metadata: Metadata = {
  title: 'UIUX Design | Creativity is central to our design',
  description: 'Generated by https://taufiqproject.my.id',
};

export default function UiUxDesignPage() {
  return (
    <>
      <UiUxDesign />
    </>
  );
}
