import React from "react";
import type { Metadata } from "next";
import Work from "@/components/work/work";

export const metadata: Metadata = {
	title: "Work | Creativity is centar to our design",
	description: "Generated by https://taufiqproject.my.id",
};

export default function WorkPage() {
	return <Work />;
}
