import type { Metadata, Viewport } from 'next';
import '/public/css/tailwind-min.css';
import localFont from 'next/font/local';
import { GoogleTagManager } from '@next/third-parties/google';
import SmoothScrolling from '@/libs/SmoothScrolling';
import CustomCursor from '@/libs/CustomCursor';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Suspense, lazy } from 'react';
const Navbar = lazy(() => import('@/components/navbar'));
const Hamburger = lazy(() => import('@/components/hamburger'));
const Footer = lazy(() => import('@/components/footer'));
const FooterMobile = lazy(() => import('@/components/footer-mobile'));

export const metadata: Metadata = {
  title: 'Flaeup',
  description: 'Generated by https://taufiqproject.my.id',
  keywords: ['Flaeup', 'Creativity is centar to our design', 'taufiq project', 'Design Indonesia', 'Jasa Desain Indonesia'],
  publisher: 'Taufiq Project visit: https://taufiqproject.my.id',
  openGraph: {
    title: 'Flaeup | Creativity is centar to our design',
    description: 'Generated by https://taufiqproject.my.id',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const Aeonik = localFont({
  src: [
    {
      path: './fonts/Aeonik-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Aeonik-RegularItalic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/Aeonik-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Aeonik-BoldItalic.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={Aeonik.className}>
      <GoogleTagManager gtmId="GTM-WQ56FQ54" />
      <head>
        <GoogleTagManager gtmId="GTM-WQ56FQ54" />
        <link id="favicon" rel="icon" type="image/svg+xml" href="../images/favicon_blue.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9865466112569774" />
      </head>
      <body>
        <noscript>
          <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WQ56FQ54" height="0" width="0" style={{ display: 'none', visibility: 'hidden' }} title="Google Tag Manager" />
        </noscript>
        <Suspense fallback={<div>Loading...</div>}>
          <Navbar />
          <Hamburger />
          <SmoothScrolling>{children}</SmoothScrolling>
          <Footer />
          <FooterMobile />
          <CustomCursor />
        </Suspense>
        <SpeedInsights />
      </body>
    </html>
  );
}
