import type { Metadata } from "next";
import "/public/css/tailwind-min.css";
import localFont from "next/font/local";
import SmoothScrolling from "@/libs/SmoothScrolling";
import CustomCursor from "@/libs/CustomCursor";
import FaviconSwitcher from "@/libs/FaviconSwitcher";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Suspense, lazy } from "react";
const Navbar = lazy(() => import("@/components/navbar"));
const Hamburger = lazy(() => import("@/components/hamburger"));
const Footer = lazy(() => import("@/components/footer"));
const FooterMobile = lazy(() => import("@/components/footer-mobile"));

export const metadata: Metadata = {
	title: "Flaeup",
	description: "Generated by https://taufiqproject.my.id",
	keywords: [
		"Flaeup",
		"Creativity is centar to our design",
		"taufiq project",
		"Design Indonesia",
		"Jasa Desain Indonesia",
	],
	publisher: "Taufiq Project visit: https://taufiqproject.my.id",
	openGraph: {
		title: "Flaeup | Creativity is centar to our design",
		description: "Generated by https://taufiqproject.my.id",
	},
};

const Aeonik = localFont({
	src: [
		{
			path: "./fonts/Aeonik-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/Aeonik-RegularItalic.woff2",
			weight: "400",
			style: "italic",
		},
		{
			path: "./fonts/Aeonik-Bold.woff2",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/Aeonik-BoldItalic.woff2",
			weight: "700",
			style: "italic",
		},
	],
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={Aeonik.className}>
			<head>
				<link
					id="favicon"
					rel="icon"
					type="image/svg+xml"
					href="../images/favicon_blue.ico"
				/>
			</head>
			<body>
				<Suspense fallback={<div>Loading...</div>}>
					<FaviconSwitcher>
						<Navbar />
						<Hamburger />
						<SmoothScrolling>{children}</SmoothScrolling>
						<Footer />
						<FooterMobile />
						<CustomCursor />
					</FaviconSwitcher>
				</Suspense>
				<SpeedInsights />
			</body>
		</html>
	);
}
