import React from "react";
import type { Metadata } from "next";
import Navbar from "@/components/navbar.jsx";
import Hamburger from "@/components/hamburger.jsx";
import Home from "@/components/home/home.jsx";
import Footer from "@/components/footer.jsx";
import FooterMobile from "@/components/footer-mobile.jsx";

export const metadata: Metadata = {
	title: "Flaeup | Creativity is centar to our design",
	description: "Generated by https://taufiqproject.my.id",
};

export default function HomePage() {
	return (
		<>
			<Navbar />
			<Hamburger />

			<Home />

			<Footer />
			<FooterMobile />
		</>
	);
}
