import React from 'react';
import type { Metadata } from 'next';
import Home from '@/components/home/home';
import Loader from '@/components/loader';

export const metadata: Metadata = {
  title: 'Flaeup | Creativity is centar to our design',
  description: 'Generated by https://taufiqproject.my.id',
};

export default function HomePage() {
  return (
    <>
      <Loader />
      <Home />
    </>
  );
}
