import React from "react";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import Home from "@/components/home/home";
const Loader = dynamic(() => import("@/components/loader"), {
	ssr: false,
});

export const metadata: Metadata = {
	title: "Flaeup | Creativity is centar to our design",
	description: "Generated by https://taufiqproject.my.id",
};

export default function HomePage() {
	return (
		<>
			<Loader />
			<Home />
		</>
	);
}
