import React from "react";
import type { Metadata } from "next";
import Packaging from "@/components/capabilities/packaging/packaging";

export const metadata: Metadata = {
	title: "Packaging | Creativity is centar to our design",
	description: "Generated by https://taufiqproject.my.id",
};

export default function PackagingPage() {
	return (
		<>
			<Packaging />
		</>
	);
}
