import React from "react";
import type { Metadata } from "next";
import Branding from "@/components/capabilities/branding/branding";

export const metadata: Metadata = {
	title: "Branding | Creativity is centar to our design",
	description: "Generated by https://taufiqproject.my.id",
};

export default function BrandingPage() {
	return (
		<>
			<Branding />
		</>
	);
}
